services:
    david63.extservicescheck.admin.controller:
        class: david63\extservicescheck\controller\admin_controller
        arguments:
            - '@template'
            - '@language'
            - '@david63.extservicescheck.core.functions'
            - '@david63.extservicescheck.core.yml_formatter'
            - '%core.root_path%ext/david63/extservicescheck/adm/style/images'

    david63.extservicescheck.core.functions:
        class: david63\extservicescheck\core\functions
        arguments:
            - '@ext.manager'
            - '@language'

    david63.extservicescheck.core.yml_formatter:
        class: david63\extservicescheck\core\yml_formatter
        arguments:
            - '@language'
            - '@david63.extservicescheck.core.functions'
